name: login
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  provider: ^6.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
      - assets/images/fashlogo.png
      - assets/images/bg.jpg
      - assets/images/flutter.png
      - assets/images/profbg.jpg
      - assets/images/profile_default.png
      - assets/images/lightlogo4x.png
      - assets/images/loginbg.jpg
      - assets/images/loginbg2.jpg
      - assets/images/darklogo4xre.png
      - assets/images/sample1.jpg