name: login
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  provider: ^6.0.0
  image_picker: ^1.0.0
  image_cropper: ^3.0.1
  get: ^4.6.5


  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  dio: ^5.2.1+1
  flutter_appauth: ^6.0.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
      - assets/images/